version: 2
updates:
  - package-ecosystem: "pip"
    labels: []
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    labels: []
    directory: "/"
    schedule:
      interval: "weekly"
